[project]
name = "seminar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gym>=0.26.2",
    "numpy>=2.1.1",
    "pandas>=2.2.2",
    "torch>=2.4.1",
]
